In [2]:
print("lol")

lol


In [3]:
2+2


4

In [4]:
import numpy as np

In [5]:
data1= [[1,2,3,4],[5,6,7,8]]

In [6]:
arr1 = np.array(data1)

In [7]:
data1.__class__

list

In [8]:
arr1.__class__

numpy.ndarray

In [9]:
arr1.ndim

2

In [11]:
arr1.shape

(2, 4)

In [12]:
arr1.dtype

dtype('int32')

In [13]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
np.arange(15).reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [16]:
arr=np.arange(10)

In [17]:
arr[5]

5

In [18]:
arr[5:8]

array([5, 6, 7])

In [19]:
arr[5:8]=12

In [20]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [21]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [23]:
arr = np.arange(15).reshape(3,5)

In [24]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [25]:
arr[0]

array([0, 1, 2, 3, 4])

In [26]:
arr[2]

array([10, 11, 12, 13, 14])

In [27]:
arr[0,0]

0

In [28]:
arr[0,1]

1

In [29]:
import pandas as pd
import numpy as np
def adder(ele1, ele2):
    return (ele1+ele2)

df = pd.DataFrame(np.random.randn(5,3) , columns=['co1','col2','col3','col4'])
df.pipe(adder,2)

ValueError: Shape of passed values is (3, 5), indices imply (4, 5)